steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: "bash"
  args: 
    - "-c"
    - |
        echo "sending the request..."
        curl -m 70 -X POST http://us-central1-tpu-prod-env-one-vm.cloudfunctions.net/dag-trigger-http -H "Content-Type: application/json" -d "{\"dag_id\":\"composer_sample_trigger_response_dag\"}" -v